vagrant: Ported Vagrantfile from MVP.
projectatomic/commissaire pull request #41
Opened 2016-11-01 17:54 UTC by ashcrow

2016-11-01 17:54 UTC, ashcrow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [multi-host-mgr-2] Port vagrant file](https://trello.com/c/vjXhv8Az/531-3-multi-host-mgr-2-port-vagrant-file)

2016-11-02 02:54 UTC, gbraad commented on doc/development.rst
> +
You have dropped the actual `vagrant up` command.

2016-11-02 15:16 UTC, ashcrow commented on doc/development.rst
> +
Added it back in. Thanks!

2016-11-07 16:01 UTC, mbarnes requested changes

2016-11-07 16:01 UTC, mbarnes commented on doc/development.rst
> +virtualization system, vagrant installed, and have all commissaire project checked
"Project" should be plural here, right?  And not sure if "commissaire-related projects" would be clearer?

2016-11-07 16:01 UTC, mbarnes commented on Vagrantfile
> +        #sudo dnf update --setopt=tsflags=nodocs -y
Did you intend to leave this commented out?  If so, maybe just remove it then?

2016-11-07 16:01 UTC, mbarnes commented on Vagrantfile
> +      #sudo dnf update -y
Ditto above.  Was this intentional?

2016-11-07 16:01 UTC, mbarnes commented on Vagrantfile
> +      sudo systemctl daemon-reload
Could the `daemon-reload` be done just once at the very end after all the config tweaks are done, or do the services have to come up in sequence?  I guess I've never tested that.  Might shave a second or two off if we can get away with it.

2016-11-07 16:08 UTC, ashcrow commented on doc/development.rst
> +virtualization system, vagrant installed, and have all commissaire project checked
Yes it should.

2016-11-07 16:10 UTC, ashcrow commented on Vagrantfile
> +        #sudo dnf update --setopt=tsflags=nodocs -y
I had commented it out while testing as it was taking a long time to update. Will fix.

2016-11-07 16:10 UTC, ashcrow commented on Vagrantfile
> +      #sudo dnf update -y
Nope. Will fix.

2016-11-07 16:13 UTC, ashcrow commented on Vagrantfile
> +      sudo systemctl daemon-reload
Reorganized in the fixup.

2016-11-07 16:16 UTC, ashcrow commented
:arrow_up_small:

2016-11-07 16:25 UTC, mbarnes approved these changes

2016-11-07 16:26 UTC, merged