config: Ported initial config module.
projectatomic/commissaire pull request #5
Opened 2016-09-21 11:10 UTC by ashcrow

2016-09-21 11:15 UTC, ashcrow commented
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4owkW3Ps&#x2F;459-2-multi-host-mgr-2-port-config-code-to-commissaire"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) [multi-host-mgr-2] Port config code to commissaire</a>

2016-09-21 15:43 UTC, mbarnes commented on doc/examples/config_kube_bearer_token.rst
>         "name": "commissaire.store.kubestorehandler",
Since we ditched the kube handler, change the name to `"commissaire.storage.etcd"`.

2016-09-21 15:43 UTC, mbarnes commented on doc/examples/config_kube_client_side_certificate.rst
>           "name": "commissaire.store.kubestorehandler",
Since we ditched the kube handler, change the name to `"commissaire.storage.etcd"`.

2016-09-21 15:44 UTC, mbarnes commented on doc/examples/insecure_config.rst
>           "name": "commissaire.store.etcdstorehandler",
The name for this is `"commissaire.storage.etcd"` now.

2016-09-21 15:45 UTC, mbarnes commented on doc/examples/secure_config.rst
>           "name": "commissaire.store.etcdstorehandler",
The name for this is `"commissaire.storage.etcd"` now.

2016-09-21 15:46 UTC, mbarnes commented on test/test_config.py
> +                {'name': 'commissaire.store.etcdstorehandler'},
The name for this is `"commissaire.storage.etcd"` now.

2016-09-21 15:46 UTC, mbarnes commented on test/test_config.py
> +                'name': 'commissaire.store.etcdstorehandler',
The name for this is `"commissaire.storage.etcd"` now.

2016-09-21 15:52 UTC, mbarnes requested changes
Sorry for all the repeat comments, just copy/pasting.

Implicit in the way I rewrote `read_config_file` was to no longer integrate with `ArgumentParser`.  Being that Commissaire services would mostly likely be deployed in containers, do you still want to support specifying all this through command-line options?  (I vote no.)

2016-09-22 14:29 UTC, ashcrow commented on doc/examples/config_kube_bearer_token.rst
>         "name": "commissaire.store.kubestorehandler",
Good catch!

2016-09-22 14:30 UTC, ashcrow commented on doc/examples/config_kube_client_side_certificate.rst
>           "name": "commissaire.store.kubestorehandler",
I think we can actually remove this file since it's specific to the old ``kubestorehandler``

2016-09-22 14:34 UTC, ashcrow commented
:arrow_up:

2016-09-22 15:14 UTC, mbarnes approved these changes

2016-09-22 15:15 UTC, mbarnes commented
Squashed and merged manually.

2016-09-22 15:15 UTC, closed without merging