WIP: ContainerManagerConfig Model
projectatomic/commissaire pull request #50
Opened 2016-11-11 19:21 UTC by ashcrow

2016-11-11 19:21 UTC, ashcrow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [multi-host-mgr-2] Store ContainerManager Configuration](https://trello.com/c/plCenTg2/554-2-multi-host-mgr-2-store-containermanager-configuration)

2016-11-15 17:56 UTC, mbarnes requested changes
Looks good, just noticed a couple minor things.

2016-11-15 17:56 UTC, mbarnes commented on src/commissaire/models/__init__.py
> +       attribute holds configuration items used to define network options.
I suggest dropping the network options sentence here.  I found it a little confusing since `Network` has no `options` attribute.

2016-11-15 17:56 UTC, mbarnes commented on src/commissaire/constants.py
> +
I expected to see all the `CLUSTER_TYPE_*` constants removed.  We don't need them anymore, right?

2016-11-15 17:56 UTC, mbarnes commented on src/commissaire/models/__init__.py
> -        'type': {'type': str},
We're still early enough that we can get away with these backward-compatibility breaks, right?

At some point we may have to worry about how to migrate data for changes like this.

2016-11-15 17:56 UTC, mbarnes commented on doc/endpoints.rst
> +  {
Are you missing `"name"` here?

2016-11-15 18:43 UTC, ashcrow commented on src/commissaire/models/__init__.py
> -        'type': {'type': str},
Yup. Once we switch to ``v1`` we will need to hold compatibility.

2016-11-15 18:45 UTC, ashcrow commented on src/commissaire/models/__init__.py
> +       attribute holds configuration items used to define network options.
It does have an ``options`` attribute once it's been instantiated, but I'll go ahead and remove it to avoid confusion. :+1:

2016-11-15 18:46 UTC, ashcrow commented on src/commissaire/constants.py
> +
:+1: good catch

2016-11-15 18:50 UTC, ashcrow commented on doc/endpoints.rst
> +  {
Updated

2016-11-15 18:50 UTC, ashcrow commented
:arrow_up:

2016-11-15 18:52 UTC, mbarnes approved these changes

2016-11-15 18:52 UTC, merged

2016-11-16 21:21 UTC, mbarnes commented on doc/endpoints.rst
> +
@ashcrow Just noticed this: `cluster_manager` should be `container_manager`, right?

Several more cases in the examples below.  You mind if I just fix this without a PR?