WIP: Host Data From External Systems
projectatomic/commissaire pull request #62
Opened 2016-11-28 22:19 UTC by ashcrow

Closes #61

2016-11-28 22:19 UTC, ashcrow commented
![](https://github.trello.services/images/mini-trello-icon.png) [[multi-host-mgr-2] [spike] Design host abstraction](https://trello.com/c/TvgomncK/579-multi-host-mgr-2-spike-design-host-abstraction)

2016-11-29 15:45 UTC, ashcrow commented
/cc @gbraad @intlabs

2016-11-29 17:28 UTC, mbarnes requested changes
Some typos and other thoughts...

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +into a model which may have it's data pulled from another system
nit: it's -> its

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +Most environments Commissaire will be used in will not be greenfield. They will
Maybe define "greenfield" here, or link to a definition?  (https://en.wikipedia.org/wiki/Greenfield_project)

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +external_provider Name of the external system of record that can authoritatively provide ``Host`` information.
Could we call this "source" instead?  Simpler and, I think, just as clear.

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +A new parameter defining a ``StoreHandler`` as the default for the models it has configured woul need to
nit: woul -> would

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +traditional ``StoreHandler`` and an ``external_provider`` ``StoreHandler``. This excercise is
nit: excercise -> exercise

2016-11-29 17:28 UTC, mbarnes commented on doc/cpd/61.rst
> +be added.
Hmm... could we just say the first `StoreHandler` defined for a particular model type is its default?  I suspect that's going to be most common, and *if* it proves necessary we could add the `default` parameter later as an override.

I'm just thinking about what happens we someone (namely, me) inevitably forgets to tag one of the `StoreHandler` definitions as default.  I think we need a reasonable implicit policy.

2016-11-29 17:50 UTC, ashcrow commented on doc/cpd/61.rst
> +into a model which may have it's data pulled from another system
:+1:

2016-11-29 17:50 UTC, ashcrow commented on doc/cpd/61.rst
> +Most environments Commissaire will be used in will not be greenfield. They will
Good idea. Will do.

2016-11-29 17:50 UTC, ashcrow commented on doc/cpd/61.rst
> +external_provider Name of the external system of record that can authoritatively provide ``Host`` information.
Sure.

2016-11-29 18:04 UTC, ashcrow commented on doc/cpd/61.rst
> +be added.
That's reasonable. My thought for explicitly stating default was I thought it would be easier to implement but using the first configuration for a model shouldn't be a problem.

2016-11-29 19:43 UTC, ashcrow commented
:arrow_up: 

If all looks well please wait until tomorrow morning to merge to give folks outside of US time to review if they would like to do so.

2016-11-29 19:59 UTC, mbarnes approved these changes
Looks great!  I'll wait til tomorrow morning to merge.

2016-11-30 05:08 UTC, gbraad approved these changes
For future: I do not believe 'greenfield' and 'brownfield' not to be explained in the document. I believe you can assume them to be general terms...

2016-11-30 05:13 UTC, gbraad commented on doc/cpd/61.rst
> +cpus         Number of CPU's on the ``Host``
Shouldn't this be 'in' ?

2016-11-30 14:11 UTC, ashcrow commented on doc/cpd/61.rst
> +cpus         Number of CPU's on the ``Host``
English is hard. I think you are right. 'in' makes more sense.

2016-11-30 14:22 UTC, gbraad commented
Check... besides this it is all fine.

2016-11-30 15:06 UTC, mbarnes approved these changes

2016-11-30 15:06 UTC, merged