Fix vagrant up
projectatomic/commissaire pull request #71
Opened 2016-12-13 22:00 UTC by ashcrow

The root cause of ``vagrant up`` not starting all expected services ended up being around access to the external interfaces. By switching over to ```0.0.0.0``` the services are able to to bind. This change also adds a ``vagrantup`` tool which starts the machines in the right order and executes our workaround for ```fedora-atomic`` and ```fuse-sshfs```.

While I was in the neighborhood I updated the vagrant docs as well.

2016-12-13 22:00 UTC, ashcrow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) [multi-host-mgr-2] Implement BDD test suite for backend services](https://trello.com/c/0nnVRcdc/462-5-multi-host-mgr-2-implement-bdd-test-suite-for-backend-services)

2016-12-13 22:50 UTC, mbarnes requested changes
One small request for the docs, but otherwise awesome work!

2016-12-13 22:50 UTC, mbarnes commented on doc/development.rst
In the note below that describes the manual work-around for `fedora-atomic`, can you tack on:
"(The `./tools/vagrantup` script does this automatically.)"

2016-12-14 14:47 UTC, ashcrow commented on doc/development.rst
Sure!

2016-12-14 15:48 UTC, ashcrow commented
:arrow_up_small:

2016-12-14 16:17 UTC, mbarnes approved these changes

2016-12-14 16:19 UTC, mbarnes commented
Squashed fixup and merged manually.

2016-12-14 16:19 UTC, closed without merging